### ISSUE TITLE
[question] webpack: Could not locate the bindings file

### ISSUE THREAD

**Issue by Mupceet** [rubikscraft/qoi-img#3]
I developed a [VSCode extension](https://github.com/Mupceet/qoi-viewer/tree/webpack-test) using this library and everything worked fine until I used webpack, but apparently the size of such a extension is too large.

I refer to [this link](https://code.visualstudio.com/api/working-with-extensions/bundling-extension#using-webpack) to use webpack and it prompts the following error at runtime, I think it means that I haven't packaged `addon.node` into the project, but I don't know how to do it, could you please give some advice?

```
Activating extension 'Mupceet.qoi-viewer' failed: Could not locate the bindings file. Tried: 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/build/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/build/Debug/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/build/Release/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/out/Debug/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/Debug/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/out/Release/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/Release/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/build/default/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/compiled/16.14.2/linux/x64/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/qoi-viewer/addon-build/release/install-root/qoixx_addon.node 
→ /home/mupceet/Proj/qoi-viewer-for-vscode/q...
```

**Comment by CaramelFur** [comment]
What do you mean by the extension is too large?

And for the bindings, I'm not exactly sure what the best way is. From some quick searches it looks like it isn't even properly supported. Though with some hacks you could probably get it to work.
But honestly I would recommend a javascript-only library for a vscode extension like this. Since speed is not required for this application. And a js-only version also automatically makes your extension cross-platform, this is useful because vscode can also be run in a browser or on arm64.

**Comment by Mupceet** [comment]
Well ...... I was talking about the size of the extension package.

And you're right, I'll try this.
